### ISSUE TITLE
Wifi or cable connection?

### ISSUE THREAD

**Issue by adrianmihalko** [Genestealer/Home-Assistant-RFLink-Gateway-ESP8266#3]
It is not clear to me from the readme. Do you connect with your Home Assistant to esp-link via cable or over WiFi?

If over WiFi, what port are you using? I am trying to connect to telnet 23 manually, but I can't see any data, which are on uC Console on esp-link.

**Comment by genestealer** [comment]
I see closed the issue, did you manage to resolve the issue?

**Comment by adrianmihalko** [comment]
Yes. If I connect with telnet from terminal I can't see any data, but it works fine in Home Assistant connecting to the same port. 👍👍👍
