### ISSUE TITLE
Error on Fritzing drawing

### ISSUE THREAD

**Issue by Muller59** [Genestealer/Home-Assistant-RFLink-Gateway-ESP8266#4]
You have the power for the nodeMCU wrong, both leads connect to ground.

**Comment by genestealer** [comment]
Hi, thanks for the feedback, yes nodeMCU Vin should be connected to the 5VDC "bottom" rail of the breadboard.

**Comment by genestealer** [comment]
Resolved with updated design. https://github.com/genestealer/Home-Assistant-RFLink-Gateway-ESP8266/tree/master/Frintzing
